# Generated by Django 3.2.15 on 2023-09-26 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('persons', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Количество персон')),
                ('allergy', models.CharField(choices=[('Нет', 'Нет'), ('Рыба и морепродукты', 'Рыба и морепродукты'), ('Мясо', 'Мясо'), ('Зерновые', 'Зерновые'), ('Продукты пчеловодства', 'Продукты пчеловодства'), ('Орехи и бобовые', 'Орехи и бобовые'), ('Молочные продукты', 'Молочные продукты')], max_length=50, verbose_name='Аллергии')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('number_meals', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Количество приемов пищи')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_menu.category', verbose_name='Категория')),
                ('product', models.ManyToManyField(to='home_menu.Product', verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
