# Generated by Django 3.2 on 2023-09-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_menu', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home_menu.customer', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
